set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports atk_in]
set_property IOSTANDARD LVCMOS33 [get_ports begin_game]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property IOSTANDARD LVCMOS33 [get_ports DCS]
set_property IOSTANDARD LVCMOS33 [get_ports down_in]
set_property IOSTANDARD LVCMOS33 [get_ports DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports key_clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_data]
set_property IOSTANDARD LVCMOS33 [get_ports left_in]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports right_in]
set_property IOSTANDARD LVCMOS33 [get_ports RSET]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports up_in]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di_which_show[0]}]

#**************************vga*************************
set_property PACKAGE_PIN A4 [get_ports {R[3]}]
set_property PACKAGE_PIN C5 [get_ports {R[2]}]
set_property PACKAGE_PIN B4 [get_ports {R[1]}]
set_property PACKAGE_PIN A3 [get_ports {R[0]}]
set_property PACKAGE_PIN A6 [get_ports {G[3]}]
set_property PACKAGE_PIN B6 [get_ports {G[2]}]
set_property PACKAGE_PIN A5 [get_ports {G[1]}]
set_property PACKAGE_PIN C6 [get_ports {G[0]}]
set_property PACKAGE_PIN D8 [get_ports {B[3]}]
set_property PACKAGE_PIN D7 [get_ports {B[2]}]
set_property PACKAGE_PIN C7 [get_ports {B[1]}]
set_property PACKAGE_PIN B7 [get_ports {B[0]}]
set_property PACKAGE_PIN B12 [get_ports vs]
set_property PACKAGE_PIN B11 [get_ports hs]

#************************°å¿¨¿ØÖÆ*********************
set_property PACKAGE_PIN P18 [get_ports down_in]
set_property PACKAGE_PIN P17 [get_ports left_in]
set_property PACKAGE_PIN M17 [get_ports right_in]
set_property PACKAGE_PIN M18 [get_ports up_in]
set_property PACKAGE_PIN L16 [get_ports atk_in]
set_property PACKAGE_PIN J15 [get_ports begin_game]
set_property PACKAGE_PIN N17 [get_ports rst]

#************************¼üÅÌ*************************
set_property PACKAGE_PIN F4 [get_ports key_clk]
set_property PACKAGE_PIN B2 [get_ports key_data]

#************************ÏµÍ³Ê±ÖÓ********************
set_property PACKAGE_PIN E3 [get_ports clk]

#************************MP3************************
set_property PACKAGE_PIN E7 [get_ports CS]
set_property PACKAGE_PIN K1 [get_ports DCS]
set_property PACKAGE_PIN J2 [get_ports DREQ]
set_property PACKAGE_PIN J3 [get_ports SCLK]
set_property PACKAGE_PIN F6 [get_ports RSET]
set_property PACKAGE_PIN J4 [get_ports MOSI]

#************************ÊýÂë¹Ü*********************
set_property PACKAGE_PIN H15 [get_ports {di_led[7]}]
set_property PACKAGE_PIN L18 [get_ports {di_led[6]}]
set_property PACKAGE_PIN T11 [get_ports {di_led[5]}]
set_property PACKAGE_PIN P15 [get_ports {di_led[4]}]
set_property PACKAGE_PIN K13 [get_ports {di_led[3]}]
set_property PACKAGE_PIN K16 [get_ports {di_led[2]}]
set_property PACKAGE_PIN R10 [get_ports {di_led[1]}]
set_property PACKAGE_PIN T10 [get_ports {di_led[0]}]
set_property PACKAGE_PIN U13 [get_ports {di_which_show[7]}]
set_property PACKAGE_PIN K2 [get_ports {di_which_show[6]}]
set_property PACKAGE_PIN T14 [get_ports {di_which_show[5]}]
set_property PACKAGE_PIN P14 [get_ports {di_which_show[4]}]
set_property PACKAGE_PIN J14 [get_ports {di_which_show[3]}]
set_property PACKAGE_PIN T9 [get_ports {di_which_show[2]}]
set_property PACKAGE_PIN J18 [get_ports {di_which_show[1]}]
set_property PACKAGE_PIN J17 [get_ports {di_which_show[0]}]

#***************************·ÀÖ¹´íÎó¾¯¸æ******************
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets begin_game_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_IBUF]


