# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/game.xdc

# IP: ip/rom_start_music/rom_start_music.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_start_music || ORIG_REF_NAME==rom_start_music} -quiet] -quiet
