# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/verilog_projects/test090_plane_war/test090_plane_war.srcs/sources_1/ip/rom_bg_image/rom_bg_image.xci
# IP: The module: 'rom_bg_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_projects/test090_plane_war/test090_plane_war.srcs/sources_1/ip/rom_bg_image/rom_bg_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bg_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/verilog_projects/test090_plane_war/test090_plane_war.srcs/sources_1/ip/rom_bg_image/rom_bg_image.xci
# IP: The module: 'rom_bg_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_projects/test090_plane_war/test090_plane_war.srcs/sources_1/ip/rom_bg_image/rom_bg_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bg_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
